#!/bin/sh

ICON="/home/pocke/bin/sound/sound_"
MSG=`amixer sset Master 10%+ | grep '\[*\]'`
#echo "${MSG}"
if [ `echo ${MSG} | grep '(\[[1-9]%\])|(\[[1-3].%\])' -cE` = '1' ]; then
  ICON="${ICON}1.png"
elif [ `echo ${MSG} | grep '\[[4-6].%\]' -cE` = '1' ]; then
  ICON="${ICON}2.png"
elif [ `echo ${MSG} | grep '(\[[7-9].%\])|(\[100%\])' -cE` = '1' ]; then
  ICON="${ICON}max.png"
fi
echo ${ICON}
notify-send -i ${ICON} "volume" "${MSG}"
